kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
networking:
  podSubnet: "172.16.0.0/12"
---
kind: InitConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
localAPIEndpoint:
  advertiseAddress: "192.168.100.1"
#nodeRegistration:
#  ignorePreflightErrors:
#    - SystemVerification  # unprivileged LXC
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
#cgroupDriver: cgroupfs  # unprivileged LXC
---
kind: KubeProxyConfiguration
apiVersion: kubeproxy.config.k8s.io/v1alpha1
#conntrack:
#  maxPerCore: 0  # unprivileged LXC
