kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
networking:
  podSubnet: "172.16.0.0/12"
---
kind: InitConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
localAPIEndpoint:
  advertiseAddress: "192.168.100.1"
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
