apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: imageproxy-ingress
spec:
  rules:
  - host: imageproxy
    http:
      paths:
      - backend:
          serviceName: imageproxy
          servicePort: 80
